#!/bin/bash

title='J-Link.*Terms of use'
display=${DISPLAY:-':0'} # use ":0" if DISPLAY unset

if xdo=$( type -P xdotool ); then
	unset -v SCREEN WINDOW X Y WIDTH HEIGHT
	export DISPLAY=$display
	eval $( $xdo search --name "$title" getwindowgeometry --shell )
	if [[ -n $SCREEN && -n $WINDOW && -n $X && -n $Y && -n $WIDTH && -n $HEIGHT ]]; then
		$xdo windowactivate --sync $WINDOW
		$xdo mousemove --sync 0 0
		$xdo mousemove --sync --window $WINDOW --screen $SCREEN 20 $(( $HEIGHT - 30 ))
		$xdo click --window $WINDOW --clearmodifiers 1
		$xdo key --window $WINDOW --clearmodifiers Alt+a
	else
		printf -- 'error: window not found: %s\n' "$title"
	fi
else
  printf -- 'error: required command not found: %s\n' "xdotool"
fi
